### ISSUE TITLE
mise à dispo des json de programme

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2015#107]
Afin d'avoir les données accessibles sur l'application mobile, il faudrait que qu'il puisse accéder au programme

**Comment by jlandure** [comment]
bah de toute façon c'est un json pour l'appli web ? :/
suffit de reprendre le même nom ?

**Comment by jefBinomed** [comment]
oui et non pas encore pour l'instant, dans peu de temps ça sera le cas, mais aujourd'hui le programme est dans le js sous forme d'objets afin d'éviter des requêtes suppl

**Comment by jlandure** [comment]
#fail

**Comment by jefBinomed** [comment]
bah en soit oui et non ? on est bien limité par le nombre de requêtes ?

**Comment by jefBinomed** [comment]
https://github.com/GDG-Nantes/devFestSite-2015/commit/b7235c9cf6c23dd0d3137e801af7ca6d831794af

**Comment by jlandure** [comment]
l'autre il avait déjà fermé l'issue alors que ça marchait pas :-1: 

<img width="498" alt="capture d ecran 2015-09-23 a 23 12 14" src="https://cloud.githubusercontent.com/assets/525974/10059006/bdd586b8-6248-11e5-859b-f968485aa666.png">

**Comment by jlandure** [comment]
d'ailleurs si c'est pour devquest, il faudrait mieux indiquer : "url - devquest " au lieu d'ouvrir à tout le monde ;)

**Comment by jefBinomed** [comment]
c'était pas pour devquest mais pour l'appli mobile sur laquelle le stagiaire bosse

**Comment by jefBinomed** [comment]
mais alors du coup, c'est bon ou pas ?

**Comment by jlandure** [comment]
oui mais l'idéal est de bloque la requête au domaine de l'appli de ton stagiaire ^^
Ca sera quoi comme adresse de site web ?

**Comment by jefBinomed** [comment]
Bah en fait, ça serait une application hybride IOS et Android du coup, tu n'aurais pas d'adresse de site web :(

Et là ils viennent de me faire remarquer qu'ils peuvent pas récupérer les images des speakers pour la même raison... Je me demande si on aurait pas intérêt à créer un projet à part pour exposer ça ?

**Comment by jlandure** [comment]
re ! si c'est une appli... y'a pas de problème de CORS en théorie...
CORS = un site/domaine accède aux données d'un autre site...
du coup je comprend pas le pb...

**Comment by jefBinomed** [comment]
ué mais c'est une webview qui fait l'appel :p d'où le CORS

**Comment by jlandure** [comment]
ok bon on ferme du coup...

**Comment by jefBinomed** [comment]
ué
