### ISSUE TITLE
ajouter le talk sous le speaker dans la partie speakers

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2015#112]

**Comment by jefBinomed** [comment]
penses aussi à ajout la salle du coup

**Comment by jlandure** [comment]
des news ?

**Comment by jefBinomed** [comment]
c'est en TODO ça , faut le planifier et ça sera dispo :) 

Pour l'instant, j'ai pas eu le temps de faire le gros json pour faciliter ça

**Comment by jlandure** [comment]
on l'a dans le projet le gros json. Il s'appelle `prog.json` non ?

**Comment by jefBinomed** [comment]
oui mais il est pas à jour :p je l'ai fait rapidos pour l'instant d'où le fait que c'est pas encore sec :)
