### ISSUE TITLE
demander des descriptions à certains speakers

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devFestSite-2015#115]
eissartial
tguenoux
fbeaufort
dgageot
blegras
rmenetrier
lchampenois 
amoussine-pouchkine

**Comment by jlandure** [comment]
on en est ou de ça ?

**Comment by jefBinomed** [comment]
eissartial, c'est bon
les autres au point zéro... mais je penses qu'on peut se contenter des résumés publiés ? Tant pis non ?

**Comment by pguyard** [comment]
as u want ; je trouve ça moche sur le site mais bon...

Pierrick Guyard

2015-09-28 10:29 GMT+02:00 Jean-François Garreau - Binomed <
notifications@github.com>:

**Comment by jlandure** [comment]
pas de news pourtant on leur a demandé de vérifier les infos du site dans l'email speaker ?
