### ISSUE TITLE
afficher un drapeau anglais si la conf est en anglais ?

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2015#117]

**Comment by pguyard** [comment]
Y'a déjà une mention fr ou en.

Pierrick.

**Comment by jefBinomed** [comment]
ué mais j'ai peur que les gens passent à côté

Après, j'avoue que je suis pas convaincu non plus :p

**Comment by jlandure** [comment]
on laisse comme ça ^^
