### ISSUE TITLE
Rajouter des nouveaux jeux konami code pour les écrans "agenda" / "speakers" / "L'équipe"

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2015#120]
Aujourd'ui, y a que sur l'acceuil et sur "En Pratique"

**Comment by jlandure** [comment]
je serais pour ne pas forcément le mettre partout :p

**Comment by jefBinomed** [comment]
au moins dans l'agenda ?

**Comment by jefBinomed** [comment]
après, si on trouve des jeux c'est facile à intégrer car en fait c'est juste une iframe qui est loadé quand le konami code est lancé

**Comment by jefBinomed** [comment]
On peut éventuellement intégrer ça facilement : 

https://github.com/cykod/AlienInvasion
https://github.com/natetarrh/frogger
http://codepen.io/anthdeldev/pen/ywbag

ça fait 3 jeux pour les 3 pages qu'il reste :p
