### ISSUE TITLE
tester le partage du site web avec twitter et facebook et gplus pour vérifier la card créé correspond à nos metadonnées

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2015#14]

**Comment by jlandure** [comment]
Il faudrait voir choisir une photo correspondant à notre site où alors mettre en lien la vidéo lorsqu'elle sera dispo publiquement.
Aujourd'hui sur FB, ça met le logo "GDG DevFest Season 2014" en gros... pas terrible donc! pareil pour G+.
pour tester sous Twitter : https://cards-dev.twitter.com/validator

**Comment by xavmarc** [comment]
Pour facebook il y a cet outil https://developers.facebook.com/tools/debug/

**Comment by pguyard** [comment]
Toujours ko sur facebook car la version en prod n'a pas la bonne image ; faut attendre une mep pour valider l'issue.

**Comment by jlandure** [comment]
Tu peux tester le partage d'une version particulière !
Pas besoin de MEP :p
Ex : http://v1-retro.devfestnantes2015.appspot.com/ ou
http://v3.devfestnantes2015.appspot.com/

Le mer. 13 mai 2015 à 17:25, Pierrick Guyard notifications@github.com a
écrit :

**Comment by pguyard** [comment]
nop si je test retro on a une canonical URL positionné à http://devfest.gdgnantes.com/
ce qui ramène http://devfest.gdgnantes.com/img/seo/sharing-facebook.png (image avec 2014) au lieu de http://devfest.gdgnantes.com/img/seo/sharing.png (image non deployée)

**Comment by jlandure** [comment]
Ajouter la vidéo dans les cards

**Comment by jlandure** [comment]
cf pour twitter : https://wordpress.org/support/topic/unable-to-validate-player-card-wyoutube-video

**Comment by jlandure** [comment]
bah ça marche depuis longtemps ça ^^
