### ISSUE TITLE
Ajouter à la page presse les retour post event

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devFestSite-2015#144]
Remplacer connexion dans le header par le lien vers la page presse

http://blog.netapsys.fr/devfest-nantes-2015/

**Comment by jlandure** [comment]
J'ai commencé à changer la page pour faire un truc comme pour les speakers :+1:

**Comment by jlandure** [comment]
Il reste à compléter tous les articles avec un petit logo (pas gênant si pas optimisé vu qu'on a moins de visites !) dans presse.json
