### ISSUE TITLE
Faire marcher le menu en mode mobile

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2015#24]
le menu en haut à droite ne semble pas fonctionnel

**Comment by jlandure** [comment]
il remarche chez moi.
J'ai changé l'ordre des imports de JS

**Comment by jefBinomed** [comment]
Pour Xavier et pour moi , il ne marche toujours pas

**Comment by jefBinomed** [comment]
En fait ça ne marche pas juste en dev

**Comment by jlandure** [comment]
Salut,
ça me parait logique : en mode prod, nous avons les templates HTML chargés
au démarrage car dans le fichier 'templates.js' alors qu'en dev, on va les
chercher côté serveur d'où un temps de latence...
Au pire en dev, on peut aussi appeler le ngTemplates pour générer le
templates :)
Créé un issue pour ça si vous pensez en avoir besoin.

**Comment by jlandure** [comment]
Du coup, on ferme ce ticket et vous rouvrez un autre pour modifier le gulp si ça vous avez besoin du menu mobile en mode dev ?

**Comment by jefBinomed** [comment]
@jlandure tu peux faire le script gulp qui fait en sorte que ça marche en dev stp ?
