### ISSUE TITLE
Traduire le COD

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2015#3]

**Comment by jlandure** [comment]
pourquoi tu as mis ton contact jef ? c'est useless non ?

**Comment by jefBinomed** [comment]
car je sais pas dans le template d'origine, y avait un contact, du coup, j'ai pas trop réfléchit, j'ai mis mon contact car c'est moi qui incistait pour le COD

**Comment by jlandure** [comment]
Merci d'enlever le blabla avec ton contact. On a déjà une page team où on peut nous contacter.
