### ISSUE TITLE
erreur 4xx appengine sur '/img/seo/sharing.png'

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2015#34]
voir pourquoi /img/seo/sharing.png est utilisé sur le site et non présent.

**Comment by jlandure** [comment]
ça vient des balises meta...
`<meta name="twitter:image:src" content="http://devfest.gdgnantes.com/img/seo/sharing-twitter.png">`
et y'a le même souci pour facebook.

**Comment by pguyard** [comment]
Xavier a modifié toutes ces balises meta par /img/seo/sharing.png.
Par contre cette image n'existe pas en prod du coup on a des 404. 
Ca devrait etre réglé lors de la prochaine mep. 
On a moyen de savoir quelle version est en prod ?

**Comment by jlandure** [comment]
la V2 donc le master vieux de 2 semaines je pense.

Le mer. 13 mai 2015 à 17:19, Pierrick Guyard notifications@github.com a
écrit :
