### ISSUE TITLE
Logo 'Season 2015'

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2015#40]
La baseline du 5 n'est pas la même que le '201', ça fait moche (puis c'est pas tout à fait la même police).
Pourquoi ne pas mettre notre logo devfest directement ?

**Comment by bpetetot** [comment]
J'ai refait le texte du logo en le modifiant, Voilà ce que ça donne (comité sur la branche retro) : 
![logos](https://cloud.githubusercontent.com/assets/516360/7691142/7964d370-fdb8-11e4-80ea-c9b7675f353c.png)

J'ai tenté de mettre le logo du gdg nantes en fond, mais au rendu final sur le site, c'était vraiment moche : 
![logos2](https://cloud.githubusercontent.com/assets/516360/7691160/9b67c360-fdb8-11e4-8dd5-0e12a4b0f519.png)
