### ISSUE TITLE
Ajout d'une modal pour les infos sur le CPF

### ISSUE THREAD

**Issue by xavmarc** [GDG-Nantes/devFestSite-2015#41]

**Comment by xavmarc** [comment]
Vérifier que texte concernant le CPF est toujours correct.

**Comment by jefBinomed** [comment]
le texte est bon, je suis juste en train de checker vis à vis de SQLI si tout est clean. Histoire de pas promettre un truc pas jouable au final.

Je ferme le ticket pour l'instant et j'ouvre un autre ticket en V3 qui vise à avoir une confirmation ou non du CPF
