### ISSUE TITLE
Lisibilité en mode mobile à revoir

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devFestSite-2015#47]
test en 360x640 c'est pire en dessous - c'est quoi notre cible ?
![mobile1](https://cloud.githubusercontent.com/assets/98096/7588703/00c0fe6a-f8bf-11e4-92d1-f3fdbbf95f96.jpg)
![mobile3](https://cloud.githubusercontent.com/assets/98096/7588746/4cb4ed7c-f8bf-11e4-9f34-3fe7a2de9986.jpg)

**Comment by jefBinomed** [comment]
Le changement de font corrige normalement le truc, il faut attendre la font que Ben va choisir pour confirmer de fermer le bug

**Comment by pguyard** [comment]
ça règle pas tout mais c'est mieux en effet
