### ISSUE TITLE
Img NantesTech tronquée

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2015#65]
Je reproduis le troncage en émulation avec "Samsung Galaxy note II"

**Comment by pguyard** [comment]
assigned to me ? J'ai pas le temps de regarder ça aujourd'hui moi j'ai un
taff :p

Pierrick Guyard

**Comment by jlandure** [comment]
tu feras ça dans la semaine, je l'ai mis pour la V3 
nous c'est :palm_tree:

**Comment by jlandure** [comment]
des news ? :nail_care:
