### ISSUE TITLE
Définir des tailles pour les logos des sponsors via des classes ?

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2015#79]
Faut qu'on définisse des tailles proportionnelles au poids du sponsor comme l'année dernière

**Comment by jlandure** [comment]
on pourrait pas enlever le 

```
.partners .list-inline {
    margin-bottom: 65px;
```

et 

```
.partners ul.gold li {
    height: 78px;
}
```

**Comment by jlandure** [comment]
je rappelle les tailles max:
- silver:     max-width: 120px; max-height: 60px;
- gold:     max-width: 150px; max-height: 78px; 
- platinium: max-width: 180px; max-height: 90px;

je serais pour avoir de choses encore un peu plus grosse en distinction: 
- silver: max-width: 120px; max-height: 60px;  OK
- gold: max-width: 150px; max-height: 78px; KO
- platinium: max-width: 180px; max-height: 90px; devient GOLD
- NEW platinium: max-width: 240px; max-height: 120px; 

rq : le logo google étant plus petit que 180px, il garde sa taille originale.
Qu'en pensez-vous ?

**Comment by jefBinomed** [comment]
ok ça me va, faudra que je change plusieurs trucs car en fait la taille de colonne définit pour gdg zepellin était limité à 180px

**Comment by jlandure** [comment]
par contre le logo google n'est pas à la bonne taille.

**Comment by jlandure** [comment]
tu n'as pas fait toutes les img ?

https://v14-dot-devfestnantes2015.appspot.com/.../beapp.jpg is resized in HTML or CSS from 1596x851 to 113x60. Serving a scaled image could save 55.3KiB (99% reduction).
https://v14-dot-devfestnantes2015.appspot.com/.../nantes-tech.png is resized in HTML or CSS from 120x89 to 81x60. Serving a scaled image could save 4.3KiB (54% reduction).
https://v14-dot-devfestnantes2015.appspot.com/.../bemyapp.png is resized in HTML or CSS from 83x90 to 55x60. Serving a scaled image could save 2.2KiB (55% reduction).
https://v14-dot-devfestnantes2015.appspot.com/.../residhome.png is resized in HTML or CSS from 120x63 to 114x60. Serving a scaled image could save 736B (10% reduction).

**Comment by jefBinomed** [comment]
si pourtant... en dev c'est optimisé, à voir s'il n'y a pas eu un soucis dans le déploiement qqe part, mais quand je lance pagespeed, ils me met plus rien en optimisation d'images

**Comment by jlandure** [comment]
bah écoute quand je regarde : https://github.com/GDG-Nantes/devFestSite-2015/tree/master/img/partners
je vois que certaines img sont vieilles (sii & beapp)

_D'ailleurs beapp on a un png ou un jpg. à jarter celui qui ne sert pas_

**Comment by jefBinomed** [comment]
la beapp.jpg je suis d'accord, faut la dégager et la sii fait pas parti des images à optimisé car elle l'est déjà

**Comment by jefBinomed** [comment]
mais si tu regarde beapp.png, il a moins de 24h

**Comment by jlandure** [comment]
c'est beapp.jpg qui est utilisé pour info dans le index.html ^^
https://github.com/GDG-Nantes/devFestSite-2015/blob/master/index.html#L328

**Comment by jefBinomed** [comment]
ah :p echec !

**Comment by jefBinomed** [comment]
du coup, on peut clore ?

**Comment by jlandure** [comment]
oui ! :+1:
