### ISSUE TITLE
Ajouter Francesc en top speaker

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2015#80]
Francesc Campoy Flores, Google
image : http://campoy.cat/pic

**Comment by jlandure** [comment]
aie aie aie c'est mal écrit : c'est "Francesc Campoy Flores"

**Comment by jefBinomed** [comment]
par ce que c'est mis Francesc Campoy ? et pas Campoy Flores ?

**Comment by jlandure** [comment]
oui ! :) c'est ""Francesc Campoy Flores" son nom > http://blog.campoy.cat/

**Comment by jefBinomed** [comment]
ué mais si tu mes Campoy Flores sur index.html ça fait moche :p c'est tout décalé par rapport aux autres :p

**Comment by jlandure** [comment]
bah je m'en fous moi ^^ mais faut écrire son nom correctement :p
C'est pas sa faute si le site est pas tout à fait adéquat/responsive...

**Comment by pguyard** [comment]
on ^p
