### ISSUE TITLE
Ajouter un mécanisme de sessions favorites - côté Serveur

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devFestSite-2015#91]
Prévoir côté serveur un truc qui nous permettra de stocker les informations de façon centralisée

**Comment by jefBinomed** [comment]
Question @jlandure pour la gestion des tokens de connexion aux apis, comme on va éviter de mettre dans le repo nos tokens, tu veux gérer comme j'ai fait sur DevQuest ? ou alors passer par des variables d’environnement ?

**Comment by jlandure** [comment]
tu mets les variables d'env dans le `app.yaml`et tu me diras quel clé mettre sur le serveur ci
Pour le commit sur github, tu mets un truc bidon style `KEY_TRUC`

**Comment by jefBinomed** [comment]
le seul hic avec cette méthode c'est qu'en dev, c'est pas pratique :( ça force à avoir un gulp bizarrement gaulé... pour être capable de tester en dev quand même les bonnes clés sans pour autant les commiter ...

**Comment by jlandure** [comment]
gulp ? je vois pas du tout le rapport entre gulp et le reste :)  va falloir qu'on se voit pour ça...
