### ISSUE TITLE
Adapter la taille des images des sponsors

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devFestSite-2015#98]
# pagespeed dit:

Les images suivantes sont redimensionnées dans le code HTML ou CSS. La diffusion d'images mises à l'échelle pourrait libérer 127.8 Ko (réduction de 74%).
https://v14-dot-devfestnantes2015.appspot.com/.../beapp.jpg est redimensionné en code HTML ou CSS de 1596 x 851 à 113 x 60. Afficher une image mise à l'échelle pourrait libérer 55.3 Ko (réduction de 99%).
https://v14-dot-devfestnantes2015.appspot.com/.../gfi.png est redimensionné en code HTML ou CSS de 217 x 141 à 120 x 78. Afficher une image mise à l'échelle pourrait libérer 13.0 Ko (réduction de 69%).
https://v14-dot-devfestnantes2015.appspot.com/.../bemyapp.png est redimensionné en code HTML ou CSS de 150 x 162 à 56 x 60. Afficher une image mise à l'échelle pourrait libérer 10.9 Ko (réduction de 86%).
https://v14-dot-devfestnantes2015.appspot.com/.../residhome.png est redimensionné en code HTML ou CSS de 190 x 100 à 114 x 60. Afficher une image mise à l'échelle pourrait libérer 9.7 Ko (réduction de 64%).
https://v14-dot-devfestnantes2015.appspot.com/.../mstream_production.png est redimensionné en code HTML ou CSS de 200 x 71 à 120 x 43. Afficher une image mise à l'échelle pourrait libérer 8.4 Ko (réduction de 63%).
https://v14-dot-devfestnantes2015.appspot.com/.../codenvy.png est redimensionné en code HTML ou CSS de 237 x 40 à 120 x 20. Afficher une image mise à l'échelle pourrait libérer 6.7 Ko (réduction de 74%).
https://v14-dot-devfestnantes2015.appspot.com/.../sii.png est redimensionné en code HTML ou CSS de 139 x 90 à 120 x 78. Afficher une image mise à l'échelle pourrait libérer 4.8 Ko (réduction de 26%).
https://v14-dot-devfestnantes2015.appspot.com/.../Logo-Epitech.png est redimensionné en code HTML ou CSS de 250 x 91 à 150 x 55. Afficher une image mise à l'échelle pourrait libérer 4.8 Ko (réduction de 63%).
https://v14-dot-devfestnantes2015.appspot.com/.../devfest_zenika.png est redimensionné en code HTML ou CSS de 180 x 150 à 94 x 78. Afficher une image mise à l'échelle pourrait libérer 4.6 Ko (réduction de 72%).
https://v14-dot-devfestnantes2015.appspot.com/.../nantes-tech.png est redimensionné en code HTML ou CSS de 135 x 100 à 81 x 60. Afficher une image mise à l'échelle pourrait libérer 4.2 Ko (réduction de 64%).
https://v14-dot-devfestnantes2015.appspot.com/.../sqli.png est redimensionné en code HTML ou CSS de 250 x 117 à 150 x 70. Afficher une image mise à l'échelle pourrait libérer 3.1 Ko (réduction de 64%).
https://v14-dot-devfestnantes2015.appspot.com/.../externatic.png est redimensionné en code HTML ou CSS de 150 x 106 à 85 x 60. Afficher une image mise à l'échelle pourrait libérer 2.2 Ko (réduction de 67%).

Optimisez les images suivantes afin de réduire leur taille de 13.4 Ko (réduction de 29%).
La compression sans perte de https://v14-dot-devfestnantes2015.appspot.com/.../gfi.png pourrait libérer 6.5 Ko (réduction de 35%). Voir le contenu optimisé
La compression sans perte de https://v14-dot-devfestnantes2015.appspot.com/.../bemyapp.png pourrait libérer 4.1 Ko (réduction de 33%). Voir le contenu optimisé
La compression sans perte de https://v14-dot-devfestnantes2015.appspot.com/.../codenvy.png pourrait libérer 2.1 Ko (réduction de 24%). Voir le contenu optimisé
La compression sans perte de https://v14-dot-devfestnantes2015.appspot.com/.../devfest_zenika.png pourrait libérer 717 o (réduction de 12%). Voir le contenu optimisé

**Comment by jefBinomed** [comment]
revu avec le #79
